### ISSUE TITLE
timezone feature

### ISSUE THREAD

**Issue by highwingers** [hayalasalah/adhan.py#1]
is there anyway, code can assign timezone automatically using the Lat & Lat parameters? I dont understand the offset setting. when and why do i need to use the offset parameter?

My Goal is to return correct prayer times based upon provided lat and lng values..but i am always adjusting the time by using offsets. anyway to automate this?

**Comment by zuhairp** [comment]
Determining timezone based on latitude and longitude is a separate Hard Problem™ that requires its own careful considerations, so I left it as out of scope for this package. 

I haven't used it myself but you can use something like the package [timezonefinder ](https://pypi.org/project/timezonefinder/) to do it for you. Once you have the timezone and figured out the UTC offset in hours, you can use that for the offset parameter. 


> when and why do i need to use the offset parameter?

If you use an offset of 0, the prayer times for the location will be returned in UTC time. The offset parameter simply adds the ```offset``` number of hours to each prayer time

**Comment by highwingers** [comment]
Thank you. I am working on a similar project to stream Adhan to Google Home and bluetooth devices. Let me know if you are interested.
https://github.com/highwingers/GoogleHome_Azan
